import operator
from typing import Annotated
from typing_extensions import TypedDict


class SearchResult(TypedDict):
    sub_question: str
    content: str
    sources: list[str]


class AgentState(TypedDict):
    # The original user query
    query: str
    # Sub-questions generated by the planner (list set once by planner node)
    sub_questions: list[str]
    # Accumulated search results from parallel search nodes
    # operator.add merges lists across parallel branches
    search_results: Annotated[list[SearchResult], operator.add]
    # Final synthesized answer from the summarizer
    final_answer: str
    # Deduplicated list of all source URLs cited
    sources: list[str]
